// lib/client/browser/widgets/react/client/widget.tsx
import * as React from 'react';
import Styles from './styles';

export default function ({wrapper, props, styles, holder}: any) {
    const elements: React.ReactElement[] = [];
    elements.push(<Styles key="styles" styles={styles}/>);

    const rs = React.useState(0);
    const refresh = () => rs[1](rs[0] + 1);

    // Listen for .js bundle changes
    wrapper.changed = refresh;

    // Check for styles to be loaded
    const loaded: boolean = (() => {
        !styles.loaded && styles.ready.then(refresh);
        holder.style.display = '';
        return styles.loaded;
    })();

    const {Widget} = wrapper;
    const widget = <Widget key="widgets" {...props}/>;
    loaded && elements.push(widget);

    return (<>{elements}</>);
}

// lib/client/browser/widgets/svelte/client/widget.svelte
<script lang="ts">
    import type {StylesManager} from '@beyond-js/widgets/render/ts';
    import type {Wrapper} from './wrapper';
    import Styles from './styles.svelte';

    export let styles: StylesManager;
    export let wrapper: Wrapper;
    export let holder: HTMLSpanElement;
    export let props: Record<string, any>;

    // Check for styles to be loaded
    let {loaded} = styles;
    !styles.loaded && styles.ready.then(() => {
        holder.style.display = '';
        loaded = true;
    });

    const {Widget} = wrapper;
</script>

<Styles styles={styles}/>

{#if loaded}
    <svelte:component this={Widget} {...props}/>
{/if}
